version: "3.9"
name: serai-dev

volumes:
  serai-node:
  serai-alice:
  serai-bob:
  serai-charlie:
  serai-dave:
  serai-eve:
  serai-ferdie:
<<<<<<< HEAD

services:
<<<<<<< HEAD
  # Coin services

  bitcoin:
    profiles:
      - bitcoin
      - coins
    build:
      context: ./coins/bitcoin/
    restart: unless-stopped
    volumes:
      - "./coins/bitcoin/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh
    ports:
      - "18443:18443"

  ethereum:
    profiles:
      - ethereum
      - coins
    build:
      context: ./coins/ethereum/
    restart: unless-stopped
    volumes:
      - "./coins/ethereum/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  monero:
    profiles:
      - monero
      - coins
    build:
      context: ./coins/monero/
    restart: unless-stopped
    volumes:
      - "./coins/monero/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh
    ports:
      - "18081:18081"

  # Infrastructure

  message-queue:
    profiles:
      - message-queue
    build:
      context: ../
      dockerfile: ./deploy/message-queue/Dockerfile
    restart: unless-stopped
    volumes:
      - "./message-queue/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh
    ports:
      - "2287:2287"

  processor:
    profiles:
      - processor
    build:
      context: ../
      dockerfile: ./deploy/processor/Dockerfile
    restart: unless-stopped
    volumes:
      - "./processor/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  # Serai services

=======
>>>>>>> e3fc3f28 (Configure node for a multi-node testnet)
=======
  genesis-service-volume:

services:
  genesis-service:
    image: serai-genesis-service:dev
    build:
      context: ./genesis-service/
      dockerfile: Dockerfile
    entrypoint: /entry-dev.sh
    volumes:
      - genesis-service-volume:/temp

>>>>>>> d2e0b58c (created shared volume between containers)
  _serai:
    &serai_defaults
    restart: unless-stopped
    image: serai:dev
    profiles:
      - _
    build:
      context: ../
      dockerfile: ./deploy/serai/Dockerfile
      args:
        TAG: serai
    entrypoint: /scripts/entry-dev.sh
    volumes:
      - "./serai/scripts:/scripts"
      - genesis-service-volume:/temp
    depends_on:
      - genesis-service

  serai-node:
    <<: *serai_defaults
    hostname: serai-node
    profiles:
      - serai
    environment:
      CHAIN: local
<<<<<<< HEAD
      NAME: node
=======
      NAME: base
>>>>>>> 083198ec (Make the dev profile a local testnet profile)

  serai-alice:
    <<: *serai_defaults
    hostname: serai-alice
    profiles:
      - alice
      - cluster-sm
      - cluster-lg
    environment:
<<<<<<< HEAD
<<<<<<< HEAD
      CHAIN: local
=======
      CHAIN: dev
>>>>>>> e3fc3f28 (Configure node for a multi-node testnet)
=======
      CHAIN: local
>>>>>>> 083198ec (Make the dev profile a local testnet profile)
      NAME: alice
      VALIDATOR: true

  serai-bob:
    <<: *serai_defaults
    hostname: serai-bob
    profiles:
      - bob
      - cluster-sm
      - cluster-lg
    environment:
<<<<<<< HEAD
<<<<<<< HEAD
      CHAIN: local
=======
      CHAIN: dev
>>>>>>> e3fc3f28 (Configure node for a multi-node testnet)
=======
      CHAIN: local
>>>>>>> 083198ec (Make the dev profile a local testnet profile)
      NAME: bob
      VALIDATOR: true

  serai-charlie:
    <<: *serai_defaults
    hostname: serai-charlie
    profiles:
      - charlie
      - cluster-sm
      - cluster-lg
    environment:
<<<<<<< HEAD
<<<<<<< HEAD
      CHAIN: local
=======
      CHAIN: dev
>>>>>>> e3fc3f28 (Configure node for a multi-node testnet)
=======
      CHAIN: local
>>>>>>> 083198ec (Make the dev profile a local testnet profile)
      NAME: charlie
      VALIDATOR: true

  serai-dave:
    <<: *serai_defaults
    hostname: serai-dave
    profiles:
      - dave
      - cluster-lg
    environment:
<<<<<<< HEAD
<<<<<<< HEAD
      CHAIN: local
=======
      CHAIN: dev
>>>>>>> 2182b664 (Correct Serai d-f names in Docker)
=======
      CHAIN: local
>>>>>>> 083198ec (Make the dev profile a local testnet profile)
      NAME: dave

  serai-eve:
    <<: *serai_defaults
    hostname: serai-eve
    profiles:
      - eve
      - cluster-lg
    environment:
<<<<<<< HEAD
<<<<<<< HEAD
      CHAIN: local
=======
      CHAIN: dev
>>>>>>> 2182b664 (Correct Serai d-f names in Docker)
=======
      CHAIN: local
>>>>>>> 083198ec (Make the dev profile a local testnet profile)
      NAME: eve

  serai-ferdie:
    <<: *serai_defaults
    hostname: serai-ferdie
    profiles:
      - ferdie
      - cluster-lg
    environment:
<<<<<<< HEAD
<<<<<<< HEAD
      CHAIN: local
      NAME: ferdie
=======
      CHAIN: dev
=======
      CHAIN: local
>>>>>>> 083198ec (Make the dev profile a local testnet profile)
      NAME: ferdie

  # Processor Services

  # Coin Services
  bitcoin:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - bitcoin
    build:
      context: ./coins/bitcoin/
    restart: unless-stopped
    volumes:
      - "./coins/bitcoin/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  ethereum:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - ethereum
    build:
      context: ./coins/ethereum/
    restart: unless-stopped
    volumes:
      - "./coins/ethereum/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh

  monero:
    profiles:
      - single-coins
      - cluster-coins-sm
      - cluster-coins-lg
      - coins
      - monero
    build:
      context: ./coins/monero/
    restart: unless-stopped
    volumes:
      - "./coins/monero/scripts:/scripts"
    entrypoint: /scripts/entry-dev.sh
    ports:
      - "18081:18081"
>>>>>>> e3fc3f28 (Configure node for a multi-node testnet)
